- name: Install PHP modules
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
    state: present

- name: Restart Apache Service
  service:
    name: apache2
    state: restarted