- name: Download WordPress
  get_url:
    url: "{{ wp_tar_url }}"
    dest: "{{ wp_tar_temp_path }}"

- name: Create Temp Directory
  file:
    dest: "{{ wp_tar_unarchive_dest }}"
    state: directory

- name: Extract WordPress Archive
  unarchive:
    src: "{{ wp_tar_temp_path }}"
    dest: "{{ wp_tar_unarchive_dest }}"
    remote_src: yes


- name: Copy WordPress to HTML
  copy:
    src: "{{ wp_tar_source }}"
    dest: "{{ wp_html }}"
    remote_src: yes