---

- hosts: webserver
  become: yes
  become_user: root



  tasks:
    - name: Install packages with loop
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - htop
        - git

    - name: Print a list
      debug:
        msg: "Hello, {{ item }}"
      with_items:
        - John
        - Jane
        - Alex
        - sarah