---
- hosts: all
  become: yes
  become_user: root
  gather_facts: no

  vars_prompt:
    - name: pkgname
      prompt: Enter package name
      private: not


  tasks:

    - name: Register a variable
      shell: cat /home/ubuntu/a.txt
      register: motd_contents

    - name: install "{{ pkgname }}"
      apt:
        name: "{{ pkgname }}"
        state: present
      when: motd_contents.stdout.find('hello') !=-1

    - name: remove "{{ pkgname }}"
      apt:
        name: "{{ pkgname }}"
        state: absent
        autoremove: yes
      when: motd_contents.stdout.find('hello') >=0