- name: Install Mysql Server and its dependencies
  apt:
    name:
      - mysql-server
      - python3-pip
      - python3-dev
      - libmysqlclient-dev
    state: present

- name: Install the python module
  pip:
    name: mysqlclient
    state: present


- name: Mysql Service management
  service:
    name: mysql
    state: started
    enabled: yes


- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present