---
  - name: Update Web Servers
    hosts: webserver
    become: yes
    become_user: root

    tasks:

      - name: Ensure apache is the latest version
        apt:
          name: apache2
          state: latest
      
      - name: Remove apache
        apt:
          name: apache2
          state: absent
          autoremove: yes

  - name: Simple Play
    hosts: webserver

    tasks:
      - name: Ping the host
        ping:
        register: pingresult

      - name: Display Result
        debug:
          var: pingresult



      