---

- hosts: webserver
  become: yes
  become_user: root

  tasks:

    - name: Install apache and php
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - git
        state: present

    - name: apache service state
      service:
        name: apache2
        state: started
        enabled: yes

- hosts: appserver
  become: yes
  become_user: root

  tasks:
    - name: Install Mysql Server
      apt:
        name:
          - mysql-server
          - python3-pip
          - git
        state: present

    - name: Install the python module
      pip:
        name: MYSQL-python
        state: present


    - name: Mysql Service
      service:
        name: mysql
        state: started
        enabled: yes


    - name: Create a new database with name 'bobdata'
      mysql_db:
        name: bobdata
        state: present

