---

- hosts: webservers
  become: yes
  become_user: root
  gather_facts: yes


  tasks:
    - name: Configure SELinux to start mysql on any port
      ansible.posix.seboolean:
        name: mysql_connect_any
        state: true
        persistent: yes
      when: ansible_selinux.status == "enabled"