---

- hosts: webservers
  become: yes
  become_user: root
  gather_facts: yes

  vars:
    epic: true
    monumental: "yes"

  tasks:
    - name: Run the command if "epic" or "monumental" is true
      debug:
        msg: echo "This certainly is epic!"
      when: epic or monumental | bool

    - name: Run the command if "epic" is false
      debug:
        msg: echo "This certainly isn't epic!"
      when: not epic